FROM python:3.10

RUN useradd -ms /bin/bash app
USER app

WORKDIR /home/app

COPY . .

RUN pip install --upgrade --quiet pip
RUN pip install -r ./requirements/development.txt

ENTRYPOINT python main.py