
version: '3.7'
services:
  redis:
    image: redis:alpine
    networks:
      - valor-stats-network

  valor-stats:
    build: .
    ports:
      - $SERVICE_PORT:$SERVICE_PORT
    env_file:
      - .env
    networks:
      - valor-stats-network
    volumes:
      - ./:/app
      - logs:/app/logs
    restart: on-failure

networks:
  valor-stats-network:

volumes:
  logs: