apiVersion: apps/v1
kind: Deployment
metadata:
  name: valor-stats-development
  labels:
    app: valor-stats

spec:
  replicas: 3
  selector:
    matchLabels:
      app: valor-stats
  template:
    metadata:
      labels:
        app: valor-stats
    spec:
      containers:
        - name: valor-stats
          image: valor-stats:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8000
